// react/ui-src/App.tsx
import React, { useEffect, useRef } from "react";
import logoPng from "./logo.png";
import logoSvg from "./logo.svg?raw";
import "./App.css";

function App() {
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    console.log(
      JSON.stringify(document.getElementById("figma-style")?.innerText)
    );
  }, []);

  const onCreate = () => {
    const count = Number(inputRef.current?.value || 0);
    parent.postMessage(
      { pluginMessage: { type: "create-rectangles", count } },
      "*"
    );
  };

  const onCancel = () => {
    parent.postMessage({ pluginMessage: { type: "cancel" } }, "*");
  };

  return (
    <div>
      <img className="logo-png" src={logoPng} />
      <img className="logo-svg" src={`data:image/svg+xml;utf8,${logoSvg}`} />
      <h2>Rectangle Creator</h2>
      <p>
        <label htmlFor="input">Count:</label>
        <input id="input" type="number" ref={inputRef} />
      </p>
      <button className="primary" onClick={onCreate}>
        Create
      </button>
      <button className="inverse" onClick={onCancel}>
        Cancel
      </button>
    </div>
  );
}

export default App;

// vue/src/App.vue
<template>
  <div>
    <img src="./logo.svg" alt="Logo">
    <h2>Rectangle Creator</h2>
    <p>
      Count:
      <input type="number" v-model.number="count" value="2" />
    </p>
    <button @click="create">Create</button>
    <button @click="cancel">Cancel</button>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      count: 2
    };
  },
  methods: {
    create: function() {
      const count = parseInt(this.count, 10);
      console.log(count);
      parent.postMessage(
        { pluginMessage: { type: "create-rectangles", count } },
        "*"
      );
    },
    cancel: function() {
      parent.postMessage({ pluginMessage: { type: "cancel" } }, "*");
    }
  },
  created() {}
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
